# Generated by Django 2.2.3 on 2019-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('auther_name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
