# Generated by Django 2.2.4 on 2019-08-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='book/images')),
                ('desc', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crudApplication.Book')),
            ],
        ),
    ]
