# Generated by Django 2.2.4 on 2019-08-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0002_bookprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookprofile',
            old_name='relation',
            new_name='book',
        ),
    ]
