# Generated by Django 2.2.4 on 2019-08-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApplication', '0003_auto_20190826_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookprofile',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='bookprofile',
            name='price',
        ),
    ]
